# Baekjoon_CLASS0_2393: Rook  
print('  ___  ___  ___')
print('  | |__| |__| |')
print('  |           |')
print('   \_________/')
print('    \_______/')
for i in range(4): print('     |     |')
print('     |_____|')
print('  __/       \__')
print(' /             \\')
print('/_______________\\')